// Dữ liệu danh mục
export const categoryData = [
  {
    id: 'all',
    name: 'Tất cả',
    icon: 'grid',
    subcategories: []
  },
  {
    id: 'food',
    name: 'Quán ăn',
    icon: 'restaurant',
    subcategories: [
      { id: 'vietnamese', name: 'Việt Nam' },
      { id: 'japanese', name: 'Nhật Bản' },
      { id: 'korean', name: 'Hàn Quốc' },
      { id: 'chinese', name: 'Trung Quốc' },
      { id: 'thai', name: 'Thái Lan' },
      { id: 'western', name: 'Phương Tây' },
      { id: 'seafood', name: 'Hải sản' },
      { id: 'bbq', name: 'Nướng BBQ' },
      { id: 'hotpot', name: 'Lẩu' },
      { id: 'vegetarian', name: 'Chay' },
    ]
  },
  {
    id: 'drink',
    name: 'Quán nước',
    icon: 'cafe',
    subcategories: [
      { id: 'coffee', name: 'Cà phê' },
      { id: 'tea', name: 'Trà' },
      { id: 'juice', name: 'Nước ép' },
      { id: 'smoothie', name: 'Sinh tố' },
      { id: 'milktea', name: 'Trà sữa' },
      { id: 'beer', name: 'Bia' },
      { id: 'wine', name: 'Rượu vang' },
      { id: 'cocktail', name: 'Cocktail' },
    ]
  },
  {
    id: 'snack',
    name: 'Ăn vặt',
    icon: 'fast-food',
    subcategories: [
      { id: 'streetfood', name: 'Đồ ăn vỉa hè' },
      { id: 'dessert', name: 'Tráng miệng' },
      { id: 'bakery', name: 'Bánh ngọt' },
      { id: 'icecream', name: 'Kem' },
      { id: 'fastfood', name: 'Đồ ăn nhanh' },
    ]
  },
  {
    id: 'specialty',
    name: 'Đặc sản',
    icon: 'star',
    subcategories: [
      { id: 'north', name: 'Miền Bắc' },
      { id: 'central', name: 'Miền Trung' },
      { id: 'south', name: 'Miền Nam' },
      { id: 'highland', name: 'Tây Nguyên' },
    ]
  },
  {
    id: 'atmosphere',
    name: 'Không gian',
    icon: 'image',
    subcategories: [
      { id: 'view', name: 'View đẹp' },
      { id: 'romantic', name: 'Lãng mạn' },
      { id: 'group', name: 'Hội họp nhóm' },
      { id: 'family', name: 'Gia đình' },
      { id: 'quiet', name: 'Yên tĩnh' },
      { id: 'outdoor', name: 'Ngoài trời' },
      { id: 'rooftop', name: 'Sân thượng' },
      { id: 'garden', name: 'Sân vườn' },
    ]
  },
];

// Dữ liệu khoảng giá
export const priceRanges = [
  { id: 'any', label: 'Mọi giá' },
  { id: '0-50000', label: 'Dưới 50K' },
  { id: '50000-150000', label: 'Từ 50K-150K' },
  { id: '150000-300000', label: 'Từ 150K-300K' },
  { id: '300000-1000000', label: 'Trên 300K' },
];

// Dữ liệu khoảng cách
export const distanceRanges = [
  { value: 0, label: 'Bất kỳ' },
  { value: 1, label: '1km' },
  { value: 3, label: '3km' },
  { value: 5, label: '5km' },
  { value: 10, label: '10km' },
  { value: 15, label: '15km' },
  { value: 20, label: '20km' },
];

// Dữ liệu ẩm thực
export const cuisineCategories = [
  { id: 'vietnamese', name: 'Việt Nam' },
  { id: 'japanese', name: 'Nhật Bản' },
  { id: 'korean', name: 'Hàn Quốc' },
  { id: 'chinese', name: 'Trung Quốc' },
  { id: 'thai', name: 'Thái Lan' },
  { id: 'western', name: 'Phương Tây' },
  { id: 'italian', name: 'Ý' },
  { id: 'french', name: 'Pháp' },
  { id: 'indian', name: 'Ấn Độ' },
  { id: 'fusion', name: 'Fusion' },
];

// Dữ liệu nhà hàng mẫu
export const restaurantsData = [
  {
    id: '1',
    name: 'Phở Hà Nội',
    type: 'Nhà hàng',
    cuisine: 'Việt Nam',
    mainCategory: 'food',
    subCategories: ['vietnamese', 'north'],
    price: '50000-100000',
    rating: 4.7,
    ratingCount: 243,
    distance: 1.2,
    address: '123 Lê Lợi, Quận 1, TP.HCM',
    openHours: '7:00 - 22:00',
    images: [
      'https://example.com/pho1.jpg',
      'https://example.com/pho2.jpg',
    ],
    coordinates: {
      latitude: 10.773491,
      longitude: 106.704774,
    },
    featured: true,
  },
  {
    id: '2',
    name: 'Cơm Tấm Sài Gòn',
    type: 'Quán ăn',
    cuisine: 'Việt Nam',
    mainCategory: 'food',
    subCategories: ['vietnamese', 'south'],
    price: '40000-80000',
    rating: 4.5,
    ratingCount: 189,
    distance: 0.8,
    address: '45 Nguyễn Huệ, Quận 1, TP.HCM',
    openHours: '6:00 - 21:00',
    images: [
      'https://example.com/comtam1.jpg',
      'https://example.com/comtam2.jpg',
    ],
    coordinates: {
      latitude: 10.772491,
      longitude: 106.702774,
    },
    featured: true,
  },
  {
    id: '3',
    name: 'Sushi Tokyo',
    type: 'Nhà hàng',
    cuisine: 'Nhật Bản',
    mainCategory: 'food',
    subCategories: ['japanese', 'seafood'],
    price: '200000-500000',
    rating: 4.8,
    ratingCount: 156,
    distance: 2.3,
    address: '78 Hai Bà Trưng, Quận 1, TP.HCM',
    openHours: '11:00 - 22:00',
    images: [
      'https://example.com/sushi1.jpg',
      'https://example.com/sushi2.jpg',
    ],
    coordinates: {
      latitude: 10.775491,
      longitude: 106.701774,
    },
    featured: false,
  },
  {
    id: '4',
    name: 'Highlands Coffee',
    type: 'Quán cà phê',
    cuisine: 'Cà phê',
    mainCategory: 'drink',
    subCategories: ['coffee', 'quiet'],
    price: '30000-90000',
    rating: 4.2,
    ratingCount: 321,
    distance: 0.5,
    address: '92 Nguyễn Du, Quận 1, TP.HCM',
    openHours: '7:00 - 22:30',
    images: [
      'https://example.com/highlands1.jpg',
      'https://example.com/highlands2.jpg',
    ],
    coordinates: {
      latitude: 10.773891,
      longitude: 106.700774,
    },
    featured: false,
  },
  {
    id: '5',
    name: 'Bún Bò Huế Gia Truyền',
    type: 'Quán ăn',
    cuisine: 'Việt Nam',
    mainCategory: 'food',
    subCategories: ['vietnamese', 'central'],
    price: '60000-120000',
    rating: 4.6,
    ratingCount: 178,
    distance: 1.8,
    address: '25 Lý Tự Trọng, Quận 1, TP.HCM',
    openHours: '6:00 - 14:00',
    images: [
      'https://example.com/bunbo1.jpg',
      'https://example.com/bunbo2.jpg',
    ],
    coordinates: {
      latitude: 10.771491,
      longitude: 106.698774,
    },
    featured: true,
  },
  {
    id: '6',
    name: 'The Coffee House',
    type: 'Quán cà phê',
    cuisine: 'Cà phê',
    mainCategory: 'drink',
    subCategories: ['coffee', 'tea', 'quiet'],
    price: '30000-80000',
    rating: 4.4,
    ratingCount: 265,
    distance: 0.7,
    address: '86 Nguyễn Huệ, Quận 1, TP.HCM',
    openHours: '7:00 - 23:00',
    images: [
      'https://example.com/coffeehouse1.jpg',
      'https://example.com/coffeehouse2.jpg',
    ],
    coordinates: {
      latitude: 10.774491,
      longitude: 106.703774,
    },
    featured: false,
  },
  {
    id: '7',
    name: 'Gogi House',
    type: 'Nhà hàng',
    cuisine: 'Hàn Quốc',
    mainCategory: 'food',
    subCategories: ['korean', 'bbq', 'group'],
    price: '150000-400000',
    rating: 4.5,
    ratingCount: 198,
    distance: 2.1,
    address: '136 Nguyễn Trãi, Quận 1, TP.HCM',
    openHours: '10:00 - 22:00',
    images: [
      'https://example.com/gogi1.jpg',
      'https://example.com/gogi2.jpg',
    ],
    coordinates: {
      latitude: 10.768491,
      longitude: 106.695774,
    },
    featured: false,
  },
  {
    id: '8',
    name: 'Bánh Mì Huỳnh Hoa',
    type: 'Quán ăn vặt',
    cuisine: 'Việt Nam',
    mainCategory: 'snack',
    subCategories: ['vietnamese', 'streetfood'],
    price: '30000-60000',
    rating: 4.9,
    ratingCount: 356,
    distance: 1.5,
    address: '26 Lê Thị Riêng, Quận 1, TP.HCM',
    openHours: '14:00 - 22:00',
    images: [
      'https://example.com/banhmi1.jpg',
      'https://example.com/banhmi2.jpg',
    ],
    coordinates: {
      latitude: 10.770491,
      longitude: 106.694774,
    },
    featured: true,
  },
  {
    id: '9',
    name: 'Phúc Long Coffee & Tea',
    type: 'Quán cà phê',
    cuisine: 'Trà sữa',
    mainCategory: 'drink',
    subCategories: ['tea', 'coffee', 'milktea'],
    price: '40000-100000',
    rating: 4.3,
    ratingCount: 287,
    distance: 0.9,
    address: '42 Nguyễn Huệ, Quận 1, TP.HCM',
    openHours: '7:00 - 22:00',
    images: [
      'https://example.com/phuclong1.jpg',
      'https://example.com/phuclong2.jpg',
    ],
    coordinates: {
      latitude: 10.772891,
      longitude: 106.703274,
    },
    featured: false,
  },
  {
    id: '10',
    name: 'Hủ Tiếu Nam Vang',
    type: 'Quán ăn',
    cuisine: 'Việt Nam',
    mainCategory: 'food',
    subCategories: ['vietnamese', 'south'],
    price: '40000-70000',
    rating: 4.6,
    ratingCount: 165,
    distance: 1.3,
    address: '84 Lý Tự Trọng, Quận 1, TP.HCM',
    openHours: '6:00 - 14:00',
    images: [
      'https://example.com/hutieu1.jpg',
      'https://example.com/hutieu2.jpg',
    ],
    coordinates: {
      latitude: 10.771991,
      longitude: 106.699774,
    },
    featured: false,
  },
  {
    id: '11',
    name: 'Pizza 4P\'s',
    type: 'Nhà hàng',
    cuisine: 'Ý',
    mainCategory: 'food',
    subCategories: ['western', 'romantic'],
    price: '200000-500000',
    rating: 4.7,
    ratingCount: 234,
    distance: 1.7,
    address: '8 Thủ Khoa Huân, Quận 1, TP.HCM',
    openHours: '11:00 - 22:00',
    images: [
      'https://example.com/pizza1.jpg',
      'https://example.com/pizza2.jpg',
    ],
    coordinates: {
      latitude: 10.773991,
      longitude: 106.702274,
    },
    featured: true,
  },
  {
    id: '12',
    name: 'Kichi Kichi',
    type: 'Nhà hàng',
    cuisine: 'Nhật Bản',
    mainCategory: 'food',
    subCategories: ['japanese', 'hotpot', 'group'],
    price: '150000-300000',
    rating: 4.4,
    ratingCount: 189,
    distance: 2.5,
    address: '76 Lê Lai, Quận 1, TP.HCM',
    openHours: '10:00 - 22:00',
    images: [
      'https://example.com/kichi1.jpg',
      'https://example.com/kichi2.jpg',
    ],
    coordinates: {
      latitude: 10.769491,
      longitude: 106.696774,
    },
    featured: false,
  },
  {
    id: '13',
    name: 'Saigon Rooftop Bar',
    type: 'Quán bar',
    cuisine: 'Cocktail',
    mainCategory: 'drink',
    subCategories: ['cocktail', 'view', 'rooftop'],
    price: '200000-500000',
    rating: 4.8,
    ratingCount: 145,
    distance: 1.9,
    address: '98 Nguyễn Huệ, Quận 1, TP.HCM',
    openHours: '17:00 - 01:00',
    images: [
      'https://example.com/rooftop1.jpg',
      'https://example.com/rooftop2.jpg',
    ],
    coordinates: {
      latitude: 10.774991,
      longitude: 106.704274,
    },
    featured: true,
  },
  {
    id: '14',
    name: 'Bánh Xèo 46A',
    type: 'Quán ăn',
    cuisine: 'Việt Nam',
    mainCategory: 'food',
    subCategories: ['vietnamese', 'south'],
    price: '70000-150000',
    rating: 4.5,
    ratingCount: 213,
    distance: 3.2,
    address: '46A Đinh Công Tráng, Quận 1, TP.HCM',
    openHours: '10:00 - 21:00',
    images: [
      'https://example.com/banhxeo1.jpg',
      'https://example.com/banhxeo2.jpg',
    ],
    coordinates: {
      latitude: 10.767491,
      longitude: 106.693774,
    },
    featured: false,
  },
  {
    id: '15',
    name: 'Maison Marou Chocolate',
    type: 'Quán cà phê',
    cuisine: 'Tráng miệng',
    mainCategory: 'snack',
    subCategories: ['dessert', 'coffee'],
    price: '100000-200000',
    rating: 4.7,
    ratingCount: 167,
    distance: 1.6,
    address: '167 Calmette, Quận 1, TP.HCM',
    openHours: '9:00 - 22:00',
    images: [
      'https://example.com/marou1.jpg',
      'https://example.com/marou2.jpg',
    ],
    coordinates: {
      latitude: 10.772491,
      longitude: 106.701774,
    },
    featured: false,
  },
  {
    id: '16',
    name: 'Trà Sữa Gong Cha',
    type: 'Quán nước',
    cuisine: 'Trà sữa',
    mainCategory: 'drink',
    subCategories: ['milktea', 'tea'],
    price: '35000-70000',
    rating: 4.2,
    ratingCount: 120,
    distance: 2.0,
    address: '12 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',
    openHours: '9:00 - 22:00',
    images: [
      'https://example.com/gongcha1.jpg',
      'https://example.com/gongcha2.jpg',
    ],
    coordinates: {
      latitude: 10.7755,
      longitude: 106.7055,
    },
    featured: false,
  },
  {
    id: '17',
    name: 'Lẩu Dê Đồng Hương',
    type: 'Nhà hàng',
    cuisine: 'Việt Nam',
    mainCategory: 'food',
    subCategories: ['vietnamese', 'hotpot', 'group'],
    price: '150000-300000',
    rating: 4.3,
    ratingCount: 98,
    distance: 3.5,
    address: '88 Trần Hưng Đạo, Quận 5, TP.HCM',
    openHours: '16:00 - 23:00',
    images: [
      'https://example.com/laude1.jpg',
      'https://example.com/laude2.jpg',
    ],
    coordinates: {
      latitude: 10.7555,
      longitude: 106.6755,
    },
    featured: false,
  },
  {
    id: '18',
    name: 'Bingsu Snowee',
    type: 'Quán ăn vặt',
    cuisine: 'Hàn Quốc',
    mainCategory: 'snack',
    subCategories: ['dessert', 'korean'],
    price: '60000-120000',
    rating: 4.6,
    ratingCount: 110,
    distance: 2.8,
    address: '45 Nguyễn Tri Phương, Quận 5, TP.HCM',
    openHours: '10:00 - 22:00',
    images: [
      'https://example.com/bingsu1.jpg',
      'https://example.com/bingsu2.jpg',
    ],
    coordinates: {
      latitude: 10.7551,
      longitude: 106.6851,
    },
    featured: false,
  },
  {
    id: '19',
    name: 'Nhà Hàng Chay Mandala',
    type: 'Nhà hàng',
    cuisine: 'Chay',
    mainCategory: 'food',
    subCategories: ['vegetarian', 'quiet'],
    price: '80000-200000',
    rating: 4.8,
    ratingCount: 90,
    distance: 2.2,
    address: '23 Nguyễn Văn Trỗi, Phú Nhuận, TP.HCM',
    openHours: '8:00 - 21:00',
    images: [
      'https://example.com/mandala1.jpg',
      'https://example.com/mandala2.jpg',
    ],
    coordinates: {
      latitude: 10.7999,
      longitude: 106.6788,
    },
    featured: true,
  },
  {
    id: '20',
    name: 'Bia Sài Gòn Chill',
    type: 'Quán bar',
    cuisine: 'Bia',
    mainCategory: 'drink',
    subCategories: ['beer', 'outdoor'],
    price: '50000-150000',
    rating: 4.1,
    ratingCount: 70,
    distance: 3.0,
    address: '100 Lê Lai, Quận 1, TP.HCM',
    openHours: '17:00 - 00:00',
    images: [
      'https://example.com/saigonchill1.jpg',
      'https://example.com/saigonchill2.jpg',
    ],
    coordinates: {
      latitude: 10.7700,
      longitude: 106.6900,
    },
    featured: false,
  },
  {
    id: '21',
    name: 'Bánh Kem Tous Les Jours',
    type: 'Tiệm bánh',
    cuisine: 'Pháp',
    mainCategory: 'snack',
    subCategories: ['bakery', 'dessert'],
    price: '40000-150000',
    rating: 4.5,
    ratingCount: 130,
    distance: 1.9,
    address: '123 Pasteur, Quận 3, TP.HCM',
    openHours: '7:00 - 22:00',
    images: [
      'https://example.com/tous1.jpg',
      'https://example.com/tous2.jpg',
    ],
    coordinates: {
      latitude: 10.7800,
      longitude: 106.6900,
    },
    featured: false,
  },
  {
    id: '22',
    name: 'Ẩm Thực Miền Trung',
    type: 'Quán ăn',
    cuisine: 'Việt Nam',
    mainCategory: 'specialty',
    subCategories: ['central', 'vietnamese'],
    price: '70000-200000',
    rating: 4.4,
    ratingCount: 85,
    distance: 4.0,
    address: '56 Nguyễn Thông, Quận 3, TP.HCM',
    openHours: '10:00 - 21:00',
    images: [
      'https://example.com/mientrung1.jpg',
      'https://example.com/mientrung2.jpg',
    ],
    coordinates: {
      latitude: 10.7850,
      longitude: 106.6950,
    },
    featured: false,
  },
  {
    id: '23',
    name: 'Nhà Hàng Tây Nguyên',
    type: 'Nhà hàng',
    cuisine: 'Tây Nguyên',
    mainCategory: 'specialty',
    subCategories: ['highland', 'vietnamese'],
    price: '100000-250000',
    rating: 4.3,
    ratingCount: 60,
    distance: 5.0,
    address: '200 Cách Mạng Tháng 8, Quận 10, TP.HCM',
    openHours: '9:00 - 22:00',
    images: [
      'https://example.com/taynguyen1.jpg',
      'https://example.com/taynguyen2.jpg',
    ],
    coordinates: {
      latitude: 10.7805,
      longitude: 106.6700,
    },
    featured: false,
  },
  {
    id: '24',
    name: 'The View Rooftop Garden',
    type: 'Quán bar',
    cuisine: 'Cocktail',
    mainCategory: 'atmosphere',
    subCategories: ['rooftop', 'view', 'romantic'],
    price: '150000-400000',
    rating: 4.7,
    ratingCount: 105,
    distance: 2.7,
    address: '195 Bùi Viện, Quận 1, TP.HCM',
    openHours: '17:00 - 01:00',
    images: [
      'https://example.com/theview1.jpg',
      'https://example.com/theview2.jpg',
    ],
    coordinates: {
      latitude: 10.7680,
      longitude: 106.6870,
    },
    featured: true,
  },
  {
    id: '25',
    name: 'Nhà Hàng Sân Vườn Xanh',
    type: 'Nhà hàng',
    cuisine: 'Việt Nam',
    mainCategory: 'atmosphere',
    subCategories: ['garden', 'family', 'outdoor'],
    price: '120000-300000',
    rating: 4.5,
    ratingCount: 112,
    distance: 3.8,
    address: '50 Phan Xích Long, Phú Nhuận, TP.HCM',
    openHours: '8:00 - 22:00',
    images: [
      'https://example.com/sanvuon1.jpg',
      'https://example.com/sanvuon2.jpg',
    ],
    coordinates: {
      latitude: 10.7990,
      longitude: 106.6800,
    },
    featured: false,
  },
];

// Thêm mock posts
export const postsData = [
  {
    id: 'p1',
    restaurantId: '1',
    content: 'Hương vị mới đã về! Thử ngay Phở đặc biệt với nước dùng đậm đà.',
    images: [
      'https://example.com/pho1.jpg',
      'https://example.com/pho2.jpg'
    ], // 2 ảnh
    likes: 120,
    comments: 15,
    tags: ['Phở', 'Món mới'],
    timePosted: '10 phút trước',
  },
  {
    id: 'p2',
    restaurantId: '2',
    content: 'Cơm tấm sườn bì chả, chuẩn vị Sài Gòn!',
    images: [
      'https://example.com/comtam1.jpg',
      'https://example.com/comtam2.jpg',
      'https://example.com/comtam3.jpg'
    ], // 3 ảnh
    likes: 98,
    comments: 8,
    tags: ['Cơm tấm', 'Sài Gòn'],
    timePosted: '30 phút trước',
  },
  {
    id: 'p3',
    restaurantId: '3',
    content: 'Sushi tươi ngon, nhập khẩu mỗi ngày.',
    images: [
      'https://example.com/sushi1.jpg',
      'https://example.com/sushi2.jpg',
      'https://example.com/sushi3.jpg',
      'https://example.com/sushi4.jpg'
    ], // 4 ảnh
    likes: 150,
    comments: 20,
    tags: ['Sushi', 'Nhật Bản'],
    timePosted: '1 giờ trước',
  },
  {
    id: 'p4',
    restaurantId: '4',
    content: 'Cà phê rang xay nguyên chất, không phụ gia.',
    images: [
      'https://example.com/highlands1.jpg',
      'https://example.com/highlands2.jpg',
      'https://example.com/highlands3.jpg',
      'https://example.com/highlands4.jpg',
      'https://example.com/highlands5.jpg'
    ], // 5 ảnh
    likes: 80,
    comments: 5,
    tags: ['Cà phê', 'Highlands'],
    timePosted: '2 giờ trước',
  },
  {
    id: 'p5',
    restaurantId: '5',
    content: 'Bún bò Huế chuẩn vị miền Trung!',
    images: ['https://example.com/bunbo1.jpg'],
    likes: 110,
    comments: 12,
    tags: ['Bún bò', 'Huế'],
    timePosted: '3 giờ trước',
  },
  {
    id: 'p6',
    restaurantId: '6',
    content: 'The Coffee House: Cold Brew Sữa Tươi đã quay trở lại!',
    images: ['https://example.com/coffeehouse1.jpg'],
    likes: 245,
    comments: 32,
    tags: ['Cà phê', 'Cold Brew'],
    timePosted: '4 giờ trước',
  },
  {
    id: 'p7',
    restaurantId: '7',
    content: 'Gogi House: Thịt nướng Hàn Quốc chuẩn vị!',
    images: ['https://example.com/gogi1.jpg'],
    likes: 132,
    comments: 15,
    tags: ['BBQ', 'Hàn Quốc'],
    timePosted: '5 giờ trước',
  },
  {
    id: 'p8',
    restaurantId: '8',
    content: 'Bánh mì Huỳnh Hoa: Đặc sản Sài Gòn!',
    images: ['https://example.com/banhmi1.jpg'],
    likes: 356,
    comments: 40,
    tags: ['Bánh mì', 'Sài Gòn'],
    timePosted: '6 giờ trước',
  },
  {
    id: 'p9',
    restaurantId: '9',
    content: 'Phúc Long: Trà sữa ưu đãi mỗi thứ 3!',
    images: ['https://example.com/phuclong1.jpg'],
    likes: 189,
    comments: 27,
    tags: ['Trà sữa', 'Ưu đãi'],
    timePosted: '7 giờ trước',
  },
  {
    id: 'p10',
    restaurantId: '10',
    content: 'Hủ tiếu Nam Vang ngon đúng điệu!',
    images: ['https://example.com/hutieu1.jpg'],
    likes: 165,
    comments: 18,
    tags: ['Hủ tiếu', 'Nam Vang'],
    timePosted: '8 giờ trước',
  },
];

// Thêm mock user
export const mockUser = {
  id: 'user1',
  name: 'Người dùng demo',
  followedRestaurants: ['1', '6', '9'], // Đã theo dõi 3 quán mẫu
};

// Dữ liệu vị trí mặc định (Hồ Chí Minh)
export const defaultLocation = {
  latitude: 10.7756587,
  longitude: 106.7004238,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421,
}; 